export const jobListings: TJobListing[] = [
  {
    id: 1,
    title: "Software Engineer",
    company: "TechCorp",
    location: "San Francisco, CA",
    type: "Full-time",
    salary: "$120,000 - $150,000",
    postedDate: "2024-06-01",
    description:
      "We are looking for a skilled software engineer to join our dynamic team. You will be responsible for developing high-quality applications.",
    requirements: [
      "Bachelor's degree in Computer Science",
      "3+ years of experience in software development",
      "Proficiency in JavaScript, Python, and Java",
    ],
    responsibilities: [
      "Develop and maintain software applications",
      "Collaborate with cross-functional teams",
      "Write clean, scalable code",
    ],
    companyLogoUrl: "https://example.com/logos/techcorp.png",
  },
  {
    id: 2,
    title: "Product Manager",
    company: "InnovateX",
    location: "New York, NY",
    type: "Full-time",
    salary: "$100,000 - $130,000",
    postedDate: "2024-06-05",
    description:
      "InnovateX is seeking a product manager to drive product development from ideation to launch.",
    requirements: [
      "Bachelor's degree in Business or related field",
      "5+ years of product management experience",
      "Strong communication skills",
    ],
    responsibilities: [
      "Define product vision and strategy",
      "Work with engineering and design teams",
      "Conduct market research and analysis",
    ],
    companyLogoUrl: "https://example.com/logos/innovatex.png",
  },
  {
    id: 3,
    title: "Data Scientist",
    company: "Data Solutions",
    location: "Remote",
    type: "Contract",
    salary: "$90,000 - $110,000",
    postedDate: "2024-06-10",
    description:
      "Data Solutions is hiring a data scientist to analyze large datasets and provide actionable insights.",
    requirements: [
      "Master's degree in Data Science or related field",
      "2+ years of experience in data analysis",
      "Proficiency in Python and R",
    ],
    responsibilities: [
      "Analyze and interpret complex data",
      "Develop predictive models",
      "Collaborate with stakeholders",
    ],
    companyLogoUrl: "https://example.com/logos/datasolutions.png",
  },
  // Add more job objects as needed
  {
    id: 4,
    title: "UX Designer",
    company: "Creative Studios",
    location: "Austin, TX",
    type: "Full-time",
    salary: "$80,000 - $100,000",
    postedDate: "2024-06-12",
    description:
      "Join Creative Studios as a UX Designer to create engaging and user-friendly interfaces.",
    requirements: [
      "Bachelor's degree in Design or related field",
      "3+ years of UX design experience",
      "Proficiency in design tools like Sketch and Figma",
    ],
    responsibilities: [
      "Design user interfaces and experiences",
      "Conduct user research",
      "Create wireframes and prototypes",
    ],
    companyLogoUrl: "https://example.com/logos/creativestudios.png",
  },
  {
    id: 5,
    title: "Marketing Specialist",
    company: "MarketGurus",
    location: "Boston, MA",
    type: "Part-time",
    salary: "$50,000 - $70,000",
    postedDate: "2024-06-15",
    description:
      "MarketGurus is looking for a marketing specialist to develop and execute marketing campaigns.",
    requirements: [
      "Bachelor's degree in Marketing",
      "2+ years of marketing experience",
      "Knowledge of SEO and SEM",
    ],
    responsibilities: [
      "Create marketing strategies",
      "Manage social media accounts",
      "Analyze marketing data",
    ],
    companyLogoUrl: "https://example.com/logos/marketgurus.png",
  },
  {
    id: 6,
    title: "Sales Representative",
    company: "SalesPro",
    location: "Chicago, IL",
    type: "Full-time",
    salary: "$60,000 + Commission",
    postedDate: "2024-06-18",
    description:
      "SalesPro is hiring a sales representative to join our growing team and drive sales.",
    requirements: [
      "Bachelor's degree in Business or related field",
      "1+ years of sales experience",
      "Excellent communication skills",
    ],
    responsibilities: [
      "Identify and pursue sales leads",
      "Build and maintain client relationships",
      "Meet sales targets",
    ],
    companyLogoUrl: "https://example.com/logos/salespro.png",
  },
  {
    id: 7,
    title: "Customer Support Specialist",
    company: "SupportHub",
    location: "Remote",
    type: "Full-time",
    salary: "$40,000 - $50,000",
    postedDate: "2024-06-20",
    description:
      "SupportHub is seeking a customer support specialist to provide exceptional support to our users.",
    requirements: [
      "High school diploma or equivalent",
      "1+ years of customer support experience",
      "Strong problem-solving skills",
    ],
    responsibilities: [
      "Respond to customer inquiries",
      "Troubleshoot issues",
      "Document support interactions",
    ],
    companyLogoUrl: "https://example.com/logos/supporthub.png",
  },
  {
    id: 8,
    title: "HR Manager",
    company: "Global Enterprises",
    location: "Seattle, WA",
    type: "Full-time",
    salary: "$90,000 - $120,000",
    postedDate: "2024-06-22",
    description:
      "Global Enterprises is hiring an HR manager to oversee our human resources operations.",
    requirements: [
      "Bachelor's degree in Human Resources",
      "5+ years of HR experience",
      "Strong leadership skills",
    ],
    responsibilities: [
      "Manage HR policies and procedures",
      "Oversee recruitment and onboarding",
      "Handle employee relations",
    ],
    companyLogoUrl: "https://example.com/logos/globalenterprises.png",
  },
  {
    id: 9,
    title: "Finance Analyst",
    company: "FinCorp",
    location: "Denver, CO",
    type: "Full-time",
    salary: "$70,000 - $90,000",
    postedDate: "2024-06-25",
    description:
      "FinCorp is looking for a finance analyst to provide financial insights and support decision-making.",
    requirements: [
      "Bachelor's degree in Finance or Accounting",
      "3+ years of finance analysis experience",
      "Proficiency in Excel and financial software",
    ],
    responsibilities: [
      "Analyze financial data",
      "Prepare reports and forecasts",
      "Assist with budgeting and planning",
    ],
    companyLogoUrl: "https://example.com/logos/fincorp.png",
  },
  {
    id: 10,
    title: "Project Manager",
    company: "BuildIt",
    location: "Los Angeles, CA",
    type: "Full-time",
    salary: "$85,000 - $110,000",
    postedDate: "2024-06-28",
    description:
      "BuildIt is seeking a project manager to lead construction projects from start to finish.",
    requirements: [
      "Bachelor's degree in Construction Management or related field",
      "4+ years of project management experience",
      "PMP certification preferred",
    ],
    responsibilities: [
      "Plan and oversee projects",
      "Manage budgets and timelines",
      "Coordinate with teams and stakeholders",
    ],
    companyLogoUrl: "https://example.com/logos/buildit.png",
  },
];
